name: Deploy
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with: { version: 8 }
    - name: Install
      run: pnpm install --frozen-lockfile
    - name: Build
      run: pnpm --filter website astro build
    - name: Publish
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        command: pages publish website/dist 